Update v2ray

diff --git a/GENERADOR-VPS-MX/gerador/v2ray b/GENERADOR-VPS-MX/gerador/v2ray
--- a/GENERADOR-VPS-MX/gerador/v2ray
+++ b/GENERADOR-VPS-MX/gerador/v2ray
@@ -315,3 +315,183 @@ msg -bar
 msg -ne "Enter Para Continuar" && read enter
 ${SCPinst}/v2ray.sh
 }
+###RES
+resdata () {
+VPSsec=$(date +%s)
+local HOST="/etc/VPS-MX/v2ray/lisportt.log"
+local HOST2="/etc/VPS-MX/v2ray/lisportt.log"
+local RETURN="$(cat $HOST|cut -d'|' -f2)"
+local IDEUUID="$(cat $HOST|cut -d'|' -f1)"
+if [[ -z $RETURN ]]; then
+echo -e "----- NINGUN PUERTO REGISTRADO -----"
+return 0
+else
+i=1
+while read hostreturn ; do
+iptables -n -v -L > /etc/VPS-MX/v2ray/data1.log 
+statsss=$(cat /etc/VPS-MX/v2ray/data1.log|grep -w "tcp spt:$hostreturn quota:"|cut -d' ' -f3,4,5)
+gblim=$(cat /etc/VPS-MX/v2ray/lisportt.log|grep -w "$hostreturn"|cut -d'|' -f2)
+local contador_secuencial+="         \e[97mPUERTO: \e[93m$hostreturn \e[97m|\e[93m$statsss \e[97m|\e[93m $gblim GB  \n"  
+        
+      if [[ $i -gt 30 ]]; then
+	      echo -e "$contador_secuencial"
+	  unset contador_secuencial
+	  unset i
+	  fi
+let i++
+done <<< "$IDEUUID"
+
+[[ ! -z $contador_secuencial ]] && {
+linesss=$(cat /etc/VPS-MX/v2ray/lisportt.log | wc -l)
+	      echo -e "$contador_secuencial \n Puertos Limitados: $linesss"
+	}
+fi
+msg -bar
+
+while true; do
+     echo -ne "\e[91m >> Digite Puerto a Limpiar:\033[1;92m " && read portbg
+     if [[ -z "$portbg" ]]; then
+     err_fun 17 && continue
+     elif [[ "$portbg" != +([0-9]) ]]; then
+     err_fun 16 && continue
+     elif [[ "$portbg" -gt "1000" ]]; then
+     err_fun 16 && continue
+     fi 
+     break
+done
+invaliduuid () {
+msg -bar
+echo -e "\e[91m                PUERTO INVALIDO \n$(msg -bar)"
+msg -ne "Enter Para Continuar" && read enter
+${SCPinst}/v2ray.sh
+}
+[[ $(sed -n '/'${portbg}'/=' /etc/VPS-MX/v2ray/lisportt.log|head -1) ]] || invaliduuid
+gblim=$(cat /etc/VPS-MX/v2ray/lisportt.log|grep -w "$portbg"|cut -d'|' -f3)
+sudo iptables -D OUTPUT -p tcp --sport $portbg -j DROP
+sudo iptables -D OUTPUT -p tcp --sport $portbg -m quota --quota $gblim -j ACCEPT
+iptables-save > /etc/iptables/rules.v4
+lineP=$(sed -n '/'${portbg}'/=' /etc/VPS-MX/v2ray/lisportt.log)
+sed -i "${linePre}d" /etc/VPS-MX/v2ray/lisportt.log
+msg -bar
+msg -ne "Enter Para Continuar" && read enter
+${SCPinst}/v2ray.sh 
+}
+## MENU
+echo -ne "\033[1;32m [1] > " && msg -azu "$(fun_trans "LIMITAR DATA x PORT") "
+echo -ne "\033[1;32m [2] > " && msg -azu "$(fun_trans "RESETEAR DATA DE PORT") "
+echo -ne "\033[1;32m [3] > " && msg -azu "$(fun_trans "VER DATOS CONSUMIDOS") "
+echo -ne "$(msg -bar)\n\033[1;32m [0] > " && msg -bra "\e[97m\033[1;41m VOLVER \033[1;37m"
+msg -bar
+selection=$(selection_fun 3)
+case ${selection} in
+1)liport ;;
+2)resdata;;
+3)estarts;;
+0)
+${SCPinst}/v2ray.sh
+;;
+esac
+}
+
+limpiador_activador () {
+unset PIDGEN
+PIDGEN=$(ps aux|grep -v grep|grep "limv2ray")
+if [[ ! $PIDGEN ]]; then
+screen -dmS limv2ray watch -n 21600 limv2ray
+else
+#killall screen
+screen -S limv2ray -p 0 -X quit
+fi
+unset PID_GEN
+PID_GEN=$(ps x|grep -v grep|grep "limv2ray")
+[[ ! $PID_GEN ]] && PID_GEN="\e[91m [ DESACTIVADO ] " || PID_GEN="\e[92m [ ACTIVADO ] "
+statgen="$(echo $PID_GEN)"
+clear 
+clear
+msg -bar
+msg -tit
+msg -ama "          ELIMINAR EXPIRADOS | UUID V2RAY"
+msg -bar
+echo ""
+echo -e "                    $statgen " 
+echo "" 						
+msg -bar
+msg -ne "Enter Para Continuar" && read enter
+${SCPinst}/v2ray.sh
+
+}
+
+selection_fun () {
+local selection="null"
+local range
+for((i=0; i<=$1; i++)); do range[$i]="$i "; done
+while [[ ! $(echo ${range[*]}|grep -w "$selection") ]]; do
+echo -ne "\033[1;37m$(fun_trans " ► Selecione una Opcion"): " >&2
+read selection
+tput cuu1 >&2 && tput dl1 >&2
+done
+echo $selection
+}
+
+PID_GEN=$(ps x|grep -v grep|grep "limv2ray")
+[[ ! $PID_GEN ]] && PID_GEN="\e[91m [ DESACTIVADO ] " || PID_GEN="\e[92m [ ACTIVADO ] "
+statgen="$(echo $PID_GEN)"
+SPR & 
+msg -bar3
+msg -bar
+msg -tit
+msg -ama "$(fun_trans "        INSTALADOR DE V2RAY (PASO A PASO) ")"
+msg -bar
+## INSTALADOR
+echo -ne "\033[1;32m [1] > " && msg -azu "$(fun_trans "INSTALAR V2RAY") "
+echo -ne "\033[1;32m [2] > " && msg -azu "$(fun_trans "CAMBIAR PROTOCOLO") "
+echo -ne "\033[1;32m [3] > " && msg -azu "$(fun_trans "ACTIVAR TLS") "
+echo -ne "\033[1;32m [4] > " && msg -azu "$(fun_trans "CAMBIAR PUERTO V2RAY")\n$(msg -bar) "
+## CONTROLER
+echo -ne "\033[1;32m [5] > " && msg -azu "AGREGAR USUARIO UUID "
+echo -ne "\033[1;32m [6] > " && msg -azu "ELIMINAR USUARIO UUID"
+echo -ne "\033[1;32m [7] > " && msg -azu "MOSTAR USUARIOS REGISTRADOS"
+echo -ne "\033[1;32m [8] > " && msg -azu "INFORMACION DE CUENTAS"
+echo -ne "\033[1;32m [9] > " && msg -azu "ESTADISTICAS DE CONSUMO "
+echo -ne "\033[1;32m [10] > " && msg -azu "LIMITADOR POR CONSUMO\e[91m ( BETA x PORT )"
+echo -ne "\033[1;32m [11] > " && msg -azu "LIMPIADOR DE EXPIRADOS ------- $statgen\n$(msg -bar)"
+## DESISNTALAR
+echo -ne "\033[1;32m [12] > " && msg -azu "\033[1;31mDESINSTALAR V2RAY"
+echo -ne "$(msg -bar)\n\033[1;32m [0] > " && msg -bra "\e[97m\033[1;41m VOLVER \033[1;37m"
+msg -bar
+pid_inst () {
+[[ $1 = "" ]] && echo -e "\033[1;31m[OFF]" && return 0
+unset portas
+portas_var=$(lsof -V -i -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND")
+i=0
+while read port; do
+var1=$(echo $port | awk '{print $1}') && var2=$(echo $port | awk '{print $9}' | awk -F ":" '{print $2}')
+[[ "$(echo -e ${portas[@]}|grep "$var1 $var2")" ]] || {
+    portas[$i]="$var1 $var2\n"
+    let i++
+    }
+done <<< "$portas_var"
+[[ $(echo "${portas[@]}"|grep "$1") ]] && echo -e "\033[1;32m[ Servicio Activo ]" || echo -e "\033[1;31m[ Servicio Desactivado ]"
+}
+echo -e "         \e[97mEstado actual: $(pid_inst v2ray)"
+msg -bar
+# while [[ ${arquivoonlineadm} != @(0|[1-99]) ]]; do
+# read -p "Seleccione una Opcion [0-12]: " arquivoonlineadm
+# tput cuu1 && tput dl1
+# done
+selection=$(selection_fun 18)
+case ${selection} in
+1)intallv2ray;;
+2)protocolv2ray;;
+3)tls;;
+4)portv;;
+5)addusr;;
+6)delusr;;
+7)mosusr_kk;;
+8)infocuenta;;
+9)stats;;
+10)lim_port;;
+11)limpiador_activador;;
+12)unistallv2;;
+0)exit;;
+esac
